apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-conf
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.exmail.qq.com:465'  #这里是指smtp的服务器
      smtp_from: 'monitor@noohle.com'  # 邮箱from地址，一般写邮箱的用户名
      smtp_auth_username: 'monitor@noohle.com'  #邮箱的用户名
      smtp_auth_password: 'NH#201812ha11'    #邮箱的密码
      smtp_require_tls: false   # 这个配置了true导致没有报错，最后我设置成了false正常了
      wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/' # 企业微信地址
    route:
      group_by: ['alertname', 'cluster', 'service']    #可以机器标签进行报警的分组
      group_wait: 10s   #分组等待时间
      group_interval: 60s    #分组的时间间隔 
      repeat_interval: 3h     #重复报警的时间间隔
      receiver: 'alert'
    receivers:
    - name:  'alert'
      email_configs:
      - send_resolved: true
        html: '{{ template "email.html" . }}' # 设定邮箱的内容模板
        to: "3007492790@qq.com,3007492778@qq.com"  
      wechat_configs: 
      - send_resolved: true
        to_party: "1" 
        agent_id: '1000002' 
        corp_id: 'ww911f8deacc68a77f' 
        api_secret: 'Ag0ijTBOve5pI1zwa3c8mIHnu26kPlqAUTcV6-c9Wo0'
    templates:
    - '/etc/alertmanager/*.tmpl'
  wechat.tmpl: |
    {{ define "wechat.default.message" }}
    {{ range $i, $alert :=.Alerts }}
    ========监控报警===========
    告警状态：{{   .Status }}
    告警级别：{{ $alert.Labels.severity }}
    告警类型：{{ $alert.Labels.alertname }}
    告警应用：{{ $alert.Annotations.summary }}
    告警主机：{{ $alert.Labels.instance }}
    告警详情：{{ $alert.Annotations.description }}
    触发阀值：{{ $alert.Annotations.value }}
    告警时间：{{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}
    ===========end=============
    {{ end }}
    {{ end }}
  email.tmpl: |
   {{ define "email.html" }}
   <table border="1">
           <tr>
                <td>报警项</td>
                <td>报警级别</td>
                <td>报警主机</td>
                <td>报警应用</td>
                <td>报警阀值</td>
                <td>警报详情</td>
                <td>开始时间</td>
           </tr>
           {{ range $i, $alert := .Alerts }}
                <tr>
                        <td>{{ index $alert.Labels "alertname" }}</td>
                        <td>{{ index $alert.Labels "severity" }}</td>
                        <td>{{ index $alert.Labels "instance" }}</td>
                        <td>{{ index $alert.Annotations "summary" }}</td>
                        <td>{{ index $alert.Annotations "value" }}</td>
                        <td>{{ index $alert.Annotations "description" }}</td>
                        <td>{{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}</td>
                </tr>
           {{ end }}
   </table>
   {{ end }}



