apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: root_url
          value:  '%(protocol)s://%(domain)s:%(http_port)s/grafana'
        - name: domian
          value:  localhost
        - name: serve_from_sub_path
          value:  'true'
        resources:
          requests:
            cpu: 0.1
            memory: 256Mi
          limits:
            cpu: 0.5
            memory: 512Mi
        volumeMounts:
        - name: grafana
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana
        persistentVolumeClaim:
          claimName: grafana
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30030
  selector:
    app: grafana

